name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.5
  flutter_launcher_icons: ^0.12.0
  # flutter_screen_lock: ^9.0.1
  local_auth: ^2.1.5
  get: ^4.6.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  # flutter_login: ^4.1.1
  injectable: ^2.1.0

  validators: ^3.0.0
  google_sign_in: ^6.0.2
  shared_preferences: ^2.0.18
  lottie: ^2.3.0
  font_awesome_flutter: ^10.4.0
  simple_ripple_animation: ^0.0.7
  cloud_firestore: ^4.4.5
  badges: ^3.0.2
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0
  flutter_app_badger: ^1.5.0
  vibration: ^1.7.6
  permission_handler: ^10.2.0
  image_picker: ^0.8.7
  flutter_slidable: ^2.0.0
  flutter_colorpicker: ^1.0.3
  image_cropper: ^3.0.2
  path_provider: ^2.0.14
  flutter_image_compress: ^1.1.3
  firebase_storage: ^11.0.16
  photo_view: ^0.14.0
  shimmer: ^2.0.0
  firebase_dynamic_links: ^5.0.17
  go_router: ^6.5.1
  get_it: ^7.2.0
  share_plus: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/flutter_logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
